### ISSUE TITLE
Doesn't work with sway predefined layout option for particular windows

### ISSUE THREAD

**Issue by timsofteng** [artemsen/swaykbdd#3]
Hello.
I have this options for some apps:
 for_window [app_id="swappy"] input type:keyboard xkb_switch_layout 0
 for_window [app_id="fuzzel"] input type:keyboard xkb_switch_layout 0
 for_window [app_id="mpv"] input type:keyboard xkb_switch_layout 0
 
 When I go back to previous window from one of them `swaykbdd` doesn't switch to its previous layout.

**Comment by artemsen** [comment]
Hi Tim,
I can't reproduce this issue in my environment. Which version of Sway do you use?
One more detail: your mouse (and any other input device) has layout too. Please, try to use `*` instead of `type:keyboard`.

**Comment by timsofteng** [comment]
@artemsen can you reproduce it?

**Comment by artemsen** [comment]
Yes, I reproduced the problem, thank you!

This happens because Sway changes the keyboard layout _before_ the new window gets focus.
By the time the window from step `2` loses focus (and the layout save routine is triggered), rule 1 has already been applied.
So, from the `swaykbdd` perspective, it looks like an user set layout `0` and then switched to the `swappy`.

And I still have no idea how to fix it :(

**Comment by artemsen** [comment]
@timsofteng, I will be grateful if you check this fix.
There is a timeout (50ms) which is an ignored amount of time between layout change and focus loss. It works for me.

**Comment by timsofteng** [comment]
@artemsen can you please describe how to do it?

**Comment by artemsen** [comment]
Just update the package using AUR: https://aur.archlinux.org/packages/swaykbdd
Or build and install from source:
```
meson build
ninja -C build
sudo ninja -C build install
```

**Comment by timsofteng** [comment]
Looks like it works.
Thanks!
