### ISSUE TITLE
Bug with floating window

### ISSUE THREAD

**Issue by timsofteng** [artemsen/swaykbdd#4]
Hello.
I've faced up with bug with floating window.

Imagine I have two window. One window is stacked and another is floated. They have different layouts.
I put focus to stacked window and try to change layout. But it doesnt changes. Instead focus move to float window.

Here is screencast:

https://user-images.githubusercontent.com/51912173/166425145-aedb81f0-16c6-4311-bd02-0d53321b94e4.mp4

**Comment by artemsen** [comment]
Hi @timsofteng,

To be honest, I have no idea why you are getting a focus change instead of a layout switch =)
`swaykbdd` subscribes to Sway events and can send only [one](https://github.com/artemsen/swaykbdd/blob/9c4d78f2a2e4270dd605681c9eca8b0bc735fdbc/src/sway.c#L210) command: `input * xkb_switch_layout N`.

Are you sure this problem is related to swaykbdd?
Do you have any layout rules in your `~/.config/sway/config`?
Can you reproduce the problem with minimal Sway config?

**Comment by timsofteng** [comment]
@artemsen 
Looks like I have conflict keybindings.
Sorry for noise.
Closed.
